backend:
  name: git-gateway
  branch: master
  repo: jboolean/art-coop

# publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets/uploads
show_preview_links: true
local_backend: true

collections:
  - name: home
    label: 'Home sections'
    label_singular: 'section'
    folder: src/home
    extension: md
    format: yaml-frontmatter
    sortable_fields:
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hidden
        label: Hide Section
        widget: boolean
        required: false
        default: false
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: anchor
        label: Anchor
        widget: string
        required: false
        default: false
        pattern: ['^\S+$', 'Must not contain spaces']
      - name: body
        label: body
        widget: markdown
  - name: moneypot
    label: 'Moneypot sections'
    label_singular: 'section'
    folder: src/moneypot
    extension: md
    format: yaml-frontmatter
    sortable_fields:
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hidden
        label: Hide Section
        widget: boolean
        required: false
        default: false
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: anchor
        label: Anchor
        widget: string
        required: false
        default: false
        pattern: ['^\S+$', 'Must not contain spaces']
      - name: body
        label: body
        widget: markdown
  - name: carousels
    label: Carousel data
    label_singular: carousel
    description: |
      Collections of data displayed in carousels and grids
    editor:
      preview: false
    files:
      - name: people
        label: People
        label_singular: person
        file: src/_data/people.json
        fields:
          - name: people
            label_singular: person
            widget: list
            allow_add: true
            summary: '{{name}} ({{personTitle}})'
            fields:
              - name: category
                required: false
                widget: select
                options:
                  - 'Artists / Field Partners'
                  - 'Grantmakers'
              - name: name
                label: Name
                widget: string
              - name: personTitle
                label: Title
                widget: string
              - name: url
                widget: string
                pattern:
                  - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
                  - Must be a URL
      - name: interventions
        label: Interventions
        label_singular: intervention
        file: src/_data/interventions.json
        fields:
          - name: interventions
            label_singular: intervention
            widget: list
            allow_add: true
            summary: '[{{interventionType}}] {{practice}}'
            fields:
              - name: interventionType
                label: Type of intervention
                widget: select
                options:
                  - 'Internal Work'
                  - 'Governance Shifts'
                  - 'New Tools/Types of Support'
                  - 'Investment/Endowment Shifts'
                  - 'Take a Systems-Change Approach'
                  - 'Policy Advocacy'
              - name: practice
                label: Practice or action
                widget: markdown
                minimal: true
                buttons: ['italic']
                editor_components: []
                modes: ['rich_text']
              # - name: sector
              #   label: Public sector, nonprofit, or foundation work?
              #   widget: select
              #   options:
              #     - Nonprofits
              #     - Foundations
              #     - Public sector
              #     - VC / Investment
              #   default:
              #     - Nonprofits
              #     - Foundations
              #     - Public sector
              #   multiple: true
              - name: exampleColleagues
                label: Examples of colleagues who are doing this work
                widget: markdown
                minimal: true
                buttons: ['link']
                editor_components: []
                modes: ['rich_text']
              - name: legal
                label: Legal Q&A
                hint: Include links to legal Q&A
                required: false
                widget: markdown
                minimal: true
                buttons: ['link']
                editor_components: []
                modes: ['rich_text']
      # - name: links
      #   label: Learn links
      #   file: src/_data/links.json
      #   fields:
      #     - name: categories
      #       label_singular: category
      #       widget: list
      #       allow_add: true
      #       fields:
      #         - name: title
      #           label: Category title
      #           widget: string
      #         - name: links
      #           widget: list
      #           label: Links
      #           label_singular: link
      #           min: 1
      #           fields:
      #             - name: text
      #               widget: string
      #             - name: url
      #               widget: string
      #               pattern:
      #                 - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
      #                 - Must be a URL
      - name: concepts
        label: Concepts
        label_singular: concept
        file: src/_data/concepts.json
        fields:
          - name: concepts
            label_singular: concept
            widget: list
            summary: '{{conceptTitle}}'
            fields:
              - name: conceptTitle
                label: Concept title
                widget: string
              - name: conceptTitlePlural
                label: Concept Title (plural)
                required: false
                widget: string
              - name: conceptDescription
                label: Concept description
                widget: text
              - name: example
                label: Example
                required: false
                widget: markdown
                minimal: true
                buttons: ['link']
                editor_components: []
  - name: studyEvents
    label: Friday events
    label_singular: event
    extension: md
    format: yaml-frontmatter
    folder: src/events
    create: true
    delete: true
    preview_path_date_field: startDate
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: start
        widget: datetime
      - name: endDate
        label: end
        widget: datetime
      - name: cohortOnly
        label: Cohort Only
        widget: boolean
        default: false
      - name: rsvpUrl
        label: RSVP URL
        widget: string
        pattern:
          - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
          - Must be a URL
        required: false
      - name: recordingUrl
        label: Recording URL
        widget: string
        pattern:
          - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
          - Must be a URL
        required: false
      - name: captionEmbedUrl
        label: Recapd Embed URL
        widget: string
      - name: body
        label: description
        widget: markdown
